#############################################################################
# Makefile for building: Ribbons
# Generated by qmake (2.01a) (Qt 4.6.2) on: Fri Mar 30 10:46:52 2012
# Project:  Ribbons.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Ribbons.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DNGL_DEBUG -DLINUX -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Iinclude -I$(HOME)/NGL/include/ -I/usr/X11R6/include -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -L/usr/local/lib -L/$(HOME)/NGL/lib -l NGL -lGLEW -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/MainWindow.cpp \
		src/GLWindow.cpp \
		src/Camera.cpp \
		src/Axis.cpp \
		src/Ribbon.cpp \
		src/RibbonManager.cpp \
		src/Bundle.cpp \
		src/Solo.cpp \
		src/VAO.cpp \
		src/DirectedBundle.cpp \
		src/BranchBundle.cpp moc/moc_MainWindow.cpp \
		moc/moc_GLWindow.cpp
OBJECTS       = obj/main.o \
		obj/MainWindow.o \
		obj/GLWindow.o \
		obj/Camera.o \
		obj/Axis.o \
		obj/Ribbon.o \
		obj/RibbonManager.o \
		obj/Bundle.o \
		obj/Solo.o \
		obj/VAO.o \
		obj/DirectedBundle.o \
		obj/BranchBundle.o \
		obj/moc_MainWindow.o \
		obj/moc_GLWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Ribbons.pro
QMAKE_TARGET  = Ribbons
DESTDIR       = 
TARGET        = Ribbons

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Ribbons.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Ribbons.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Ribbons.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/Ribbons1.0.0 || $(MKDIR) obj/Ribbons1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/Ribbons1.0.0/ && $(COPY_FILE) --parents include/MainWindow.h include/GLWindow.h include/Camera.h include/Axis.h include/Ribbon.h include/RibbonManager.h include/Bundle.h include/Solo.h include/VAO.h include/DirectedBundle.h include/BranchBundle.h obj/Ribbons1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/MainWindow.cpp src/GLWindow.cpp src/Camera.cpp src/Axis.cpp src/Ribbon.cpp src/RibbonManager.cpp src/Bundle.cpp src/Solo.cpp src/VAO.cpp src/DirectedBundle.cpp src/BranchBundle.cpp obj/Ribbons1.0.0/ && (cd `dirname obj/Ribbons1.0.0` && $(TAR) Ribbons1.0.0.tar Ribbons1.0.0 && $(COMPRESS) Ribbons1.0.0.tar) && $(MOVE) `dirname obj/Ribbons1.0.0`/Ribbons1.0.0.tar.gz . && $(DEL_FILE) -r obj/Ribbons1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_MainWindow.cpp moc/moc_GLWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_MainWindow.cpp moc/moc_GLWindow.cpp
moc/moc_MainWindow.cpp: include/GLWindow.h \
		include/Camera.h \
		include/Axis.h \
		include/Ribbon.h \
		include/Bundle.h \
		include/RibbonManager.h \
		include/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/MainWindow.h -o moc/moc_MainWindow.cpp

moc/moc_GLWindow.cpp: include/Camera.h \
		include/Axis.h \
		include/Ribbon.h \
		include/Bundle.h \
		include/RibbonManager.h \
		include/GLWindow.h \
		include/GLWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/GLWindow.h -o moc/moc_GLWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/main.o: src/main.cpp include/MainWindow.h \
		include/GLWindow.h \
		include/Camera.h \
		include/Axis.h \
		include/Ribbon.h \
		include/Bundle.h \
		include/RibbonManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/MainWindow.o: src/MainWindow.cpp include/MainWindow.h \
		include/GLWindow.h \
		include/Camera.h \
		include/Axis.h \
		include/Ribbon.h \
		include/Bundle.h \
		include/RibbonManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MainWindow.o src/MainWindow.cpp

obj/GLWindow.o: src/GLWindow.cpp include/GLWindow.h \
		include/Camera.h \
		include/Axis.h \
		include/Ribbon.h \
		include/Bundle.h \
		include/RibbonManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GLWindow.o src/GLWindow.cpp

obj/Camera.o: src/Camera.cpp include/Camera.h \
		include/GLWindow.h \
		include/Axis.h \
		include/Ribbon.h \
		include/Bundle.h \
		include/RibbonManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Camera.o src/Camera.cpp

obj/Axis.o: src/Axis.cpp include/Axis.h \
		include/Camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Axis.o src/Axis.cpp

obj/Ribbon.o: src/Ribbon.cpp include/Ribbon.h \
		include/Axis.h \
		include/Camera.h \
		include/Bundle.h \
		include/RibbonManager.h \
		include/GLWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Ribbon.o src/Ribbon.cpp

obj/RibbonManager.o: src/RibbonManager.cpp include/RibbonManager.h \
		include/Bundle.h \
		include/Ribbon.h \
		include/Axis.h \
		include/Camera.h \
		include/GLWindow.h \
		include/Solo.h \
		include/BranchBundle.h \
		include/DirectedBundle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/RibbonManager.o src/RibbonManager.cpp

obj/Bundle.o: src/Bundle.cpp include/Bundle.h \
		include/RibbonManager.h \
		include/Camera.h \
		include/GLWindow.h \
		include/Axis.h \
		include/Ribbon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Bundle.o src/Bundle.cpp

obj/Solo.o: src/Solo.cpp include/Solo.h \
		include/Bundle.h \
		include/RibbonManager.h \
		include/Camera.h \
		include/GLWindow.h \
		include/Axis.h \
		include/Ribbon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Solo.o src/Solo.cpp

obj/VAO.o: src/VAO.cpp include/VAO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/VAO.o src/VAO.cpp

obj/DirectedBundle.o: src/DirectedBundle.cpp include/DirectedBundle.h \
		include/Bundle.h \
		include/RibbonManager.h \
		include/Camera.h \
		include/GLWindow.h \
		include/Axis.h \
		include/Ribbon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/DirectedBundle.o src/DirectedBundle.cpp

obj/BranchBundle.o: src/BranchBundle.cpp include/BranchBundle.h \
		include/Bundle.h \
		include/RibbonManager.h \
		include/Camera.h \
		include/GLWindow.h \
		include/Axis.h \
		include/Ribbon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/BranchBundle.o src/BranchBundle.cpp

obj/moc_MainWindow.o: moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_MainWindow.o moc/moc_MainWindow.cpp

obj/moc_GLWindow.o: moc/moc_GLWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_GLWindow.o moc/moc_GLWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

